-- 1. Tabelas que dependem fortemente de outras
DROP TABLE IF EXISTS Avaliacao CASCADE;
DROP TABLE IF EXISTS FeedBack CASCADE;
DROP TABLE IF EXISTS Notifica CASCADE;
DROP TABLE IF EXISTS Comunica CASCADE;
DROP TABLE IF EXISTS Mensagem CASCADE;
DROP TABLE IF EXISTS Avisos CASCADE;
DROP TABLE IF EXISTS Inscricao CASCADE;
DROP TABLE IF EXISTS Matricula CASCADE;
DROP TABLE IF EXISTS OfertaDisciplina CASCADE;
DROP TABLE IF EXISTS MinistraAula CASCADE;
DROP TABLE IF EXISTS ComporCursoDisciplina CASCADE;
DROP TABLE IF EXISTS Vinculo CASCADE;
DROP TABLE IF EXISTS PreRequisitoDisciplina CASCADE;
DROP TABLE IF EXISTS PreRequisitoCurso CASCADE;
DROP TABLE IF EXISTS Regras CASCADE;

-- 2. Tabelas intermediárias
DROP TABLE IF EXISTS Curso CASCADE;
DROP TABLE IF EXISTS Departamento CASCADE;
DROP TABLE IF EXISTS Disciplina CASCADE;

-- 3. Tabelas principais com dependências externas
DROP TABLE IF EXISTS Funcionario CASCADE;
DROP TABLE IF EXISTS Professor CASCADE;
DROP TABLE IF EXISTS Aluno CASCADE;

-- 4. Tabelas principais
DROP TABLE IF EXISTS UnidadeEscolar CASCADE;
DROP TABLE IF EXISTS Usuario CASCADE;
